Feature/check model columns have meta keys
Montreal-Analytics/dbt-gloss pull request #216
Opened 2024-04-30 12:02 UTC by roydobbe

For data catalog purposes, we would like to have an option to check the columns for specific meta keys.

This function combines check_model_columns_have_desc and check_model_has_meta_keys

2024-05-02 14:11 UTC, roydobbe commented
Hey @BAntonellini 

I made this pr for a usecase we are facing regarding our data catalog. Are you the person I should ask to have a look at it?

2024-05-03 14:21 UTC, BAntonellini requested changes
Nice contribution @roydobbe, we're sure it'd be a great addition to Checkpoint hooks. Let's discuss some details before merging.

2024-05-03 14:21 UTC, BAntonellini commented on dbt_checkpoint/check_model_columns_have_meta_keys.py
> +        else:
In which case the union from above will result in something other than `Model` or `ModelSchema`?

2024-05-03 14:21 UTC, BAntonellini commented on dbt_checkpoint/check_model_columns_have_meta_keys.py
> +        seen = missing.get(model_name)
If `L116` logic persists, couldn't `model_name` be referenced before declaration? (undefined)

2024-05-03 14:21 UTC, BAntonellini commented on dbt_checkpoint/check_model_columns_have_meta_keys.py
> +    for model, columns in missing.items():
Many details from L126 to L142:
- Couldn't results be calculated above, while traversing Model and ModelSchemas?
- Result string can surely be better handled (a multi-line template, f-strings, some auxiliary in `utils.py`, etc.)
- Aren't we open to many KeyErrors? Take into account that dict's `get` method is almost always a better approach than `if key in dict` followed by direct `[key]` access.

2024-05-03 14:21 UTC, BAntonellini commented on dbt_checkpoint/check_model_columns_have_meta_keys.py
> +    for item in itertools.chain(models, schemas):
I see many DRY candidates from here until L113

2024-05-07 08:19 UTC, roydobbe commented
Hey @BAntonellini 

I made some adjustments. Could you have a look?

2024-07-03 19:06 UTC, BAntonellini requested changes
We like it better now, though left a comment about imports

2024-07-03 19:06 UTC, BAntonellini commented on dbt_checkpoint/check_model_columns_have_meta_keys.py
> +from dbt_checkpoint.utils import yellow
Could you please group imports properly? We follow Black formatting

2025-02-12 17:36 UTC, joshuadienye commented
@BAntonellini @roydobbe  Hey. Good morning! I'm a Data Engineer at PMG and we use dbt-checkpoint and love it. I was going to make a request for this feature and also attempt to work on it. I saw this PR pending and wanted to see if there's anything I can do to help here to push it over the line. I see it's been stalling since July of last year.

2026-01-02 19:36 UTC, k0x2e commented
@roydobbe @joshuadienye New maintainer here, I'm not sure what the hold up was on this ultimately, but I am merging it into the next release.  Thank you for the contribution and the offer of help, respectively!

2026-01-02 19:37 UTC, merged