wip: Added hook: check_model_has_tests_by_group
Montreal-Analytics/dbt-gloss pull request #6
Opened 2021-02-21 03:47 UTC by jtalmi

This PR adds a hook that checks if a model has a sufficient number of tests pulled out of a group of acceptable tests, e.g. this model has 1 of unique, unique_where, or unique_threshold.

2021-02-23 12:00 UTC, tomsej commented on pre_commit_dbt/check_model_has_tests_by_group.py
> +    try:
This is not needed since argparse take care of type. Test_cnt variable is not even used (see line 79), so you can delete this whole try: part

2021-02-23 12:01 UTC, tomsej commented on pre_commit_dbt/check_model_has_tests_by_group.py
> +from pre_commit_dbt.utils import ParseDict
ParseDict is not used anywhere, please delete this line

2021-02-23 12:48 UTC, tomsej commented on pre_commit_dbt/check_model_has_tests_by_group.py
> +    try:
And this is also causing that tests fails since this exception is not tested anywhere -> test coverage < 100%

2021-02-23 16:06 UTC, tomsej requested changes
Looks great 🎉! I have run even mutation testing and all passes. Just delete unnecessary try and delete the unused import and we can merge that.

2021-02-23 16:14 UTC, jtalmi commented
> Looks great 🎉! I have run even mutation testing and all passes. Just delete unnecessary try and delete the unused import and we can merge that.

awesome. i just added a new commit to take care of requested changes.

2021-02-23 16:27 UTC, merged

2021-02-24 08:13 UTC, tomsej commented
resolve #5